import type { Alert, DashboardData, Ticket, User } from './types';
const now = Date.now();
const ago = (hours: number) => new Date(now - hours * 3600000).toISOString();
export const users: User[] = [{ id: 'u1', name: 'Maya Chen', email: 'maya@queuewise.co', role: 'supervisor' }, { id: 'u2', name: 'Jordan Lee', email: 'jordan@queuewise.co', role: 'agent' }, { id: 'u3', name: 'Sam Rivera', email: 'sam@queuewise.co', role: 'agent' }, { id: 'u4', name: 'Noah Patel', email: 'noah@queuewise.co', role: 'agent' }];
export const tickets: Ticket[] = [
    { id: 'TK-1048', subject: 'Invoice is showing the wrong tax rate', description: 'Our latest invoice has a tax rate that does not match our account settings.', requester: 'Lena Ortiz', requesterEmail: 'lena@northstar.io', priority: 'High', category: 'Billing', status: 'Open', assignee: 'Jordan Lee', assigneeId: 'u2', collaborators: ['Maya Chen'], updatedAt: ago(1), createdAt: ago(12), slaMinutes: 240, slaStartedAt: ago(220), replies: [{ id: 'r1', author: 'Lena Ortiz', body: 'Can you take a look before our renewal?', timestamp: ago(10), internal: false }, { id: 'r2', author: 'Jordan Lee', body: 'I am checking the account configuration now.', timestamp: ago(2), internal: false }], activity: [{ id: 'a1', type: 'status', text: 'New → Open', timestamp: ago(11), actor: 'Jordan Lee' }, { id: 'a2', type: 'reply', text: 'Replied to requester', timestamp: ago(2), actor: 'Jordan Lee' }] },
    { id: 'TK-1047', subject: 'SSO login loops back to sign in', description: 'Several teammates cannot access the workspace through Okta.', requester: 'Marcus Webb', requesterEmail: 'marcus@redwood.dev', priority: 'Urgent', category: 'Technical', status: 'Pending', assignee: 'Sam Rivera', assigneeId: 'u3', collaborators: [], updatedAt: ago(3), createdAt: ago(28), slaMinutes: 180, slaStartedAt: ago(100), replies: [{ id: 'r3', author: 'Sam Rivera', body: 'We have asked our identity team to validate the SAML response.', timestamp: ago(3), internal: false }, { id: 'r4', author: 'Sam Rivera', body: 'Waiting on customer to confirm the certificate thumbprint.', timestamp: ago(3), internal: true }], activity: [{ id: 'a3', type: 'status', text: 'Open → Pending', timestamp: ago(3), actor: 'Sam Rivera' }, { id: 'a4', type: 'reply', text: 'Added an internal note', timestamp: ago(3), actor: 'Sam Rivera' }] },
    { id: 'TK-1046', subject: 'How do I add a new workspace member?', description: 'Looking for the fastest way to invite our new team members.', requester: 'Priya Shah', requesterEmail: 'priya@orbitlabs.com', priority: 'Normal', category: 'How-to', status: 'New', assignee: 'Unassigned', assigneeId: '', collaborators: [], updatedAt: ago(5), createdAt: ago(5), slaMinutes: 480, slaStartedAt: ago(5), replies: [], activity: [] },
    { id: 'TK-1045', subject: 'Webhook deliveries timing out', description: 'Webhook calls have been timing out since this morning.', requester: 'Evan Brooks', requesterEmail: 'evan@fieldnote.app', priority: 'High', category: 'Technical', status: 'Resolved', assignee: 'Noah Patel', assigneeId: 'u4', collaborators: ['Jordan Lee'], updatedAt: ago(8), createdAt: ago(32), slaMinutes: 240, slaStartedAt: ago(32), replies: [{ id: 'r5', author: 'Noah Patel', body: 'The endpoint is responding normally again. We increased the timeout window.', timestamp: ago(8), internal: false }], activity: [{ id: 'a5', type: 'status', text: 'Pending → Resolved', timestamp: ago(8), actor: 'Noah Patel' }] },
    { id: 'TK-1044', subject: 'Please close our duplicate request', description: 'This was submitted twice, please close it.', requester: 'Ava King', requesterEmail: 'ava@lumen.studio', priority: 'Low', category: 'Account', status: 'Closed', assignee: 'Jordan Lee', assigneeId: 'u2', collaborators: [], updatedAt: ago(26), createdAt: ago(50), slaMinutes: 480, slaStartedAt: ago(50), replies: [], activity: [], archived: true }
];
export const dashboard: DashboardData = { stats: { open: 18, pending: 7, resolved: 42, breaching: 3 }, status: [{ name: 'Open', value: 18 }, { name: 'Pending', value: 7 }, { name: 'New', value: 6 }, { name: 'Resolved', value: 42 }], agents: [{ name: 'Jordan', value: 12 }, { name: 'Sam', value: 9 }, { name: 'Noah', value: 8 }, { name: 'Unassigned', value: 6 }], resolved: [{ week: 'Jul 15', value: 18 }, { week: 'Jul 22', value: 24 }, { week: 'Jul 29', value: 21 }, { week: 'Aug 05', value: 29 }, { week: 'Aug 12', value: 34 }, { week: 'Aug 19', value: 31 }, { week: 'Aug 26', value: 39 }, { week: 'Sep 02', value: 42 }] };
export const alerts: Alert[] = [{ id: 'TK-1047', subject: 'SSO login loops back to sign in', assignee: 'Sam Rivera', assigneeId: 'u3', minutes: -42, severity: 'breaching' }, { id: 'TK-1048', subject: 'Invoice is showing the wrong tax rate', assignee: 'Jordan Lee', assigneeId: 'u2', minutes: 20, severity: 'at-risk' }, { id: 'TK-1039', subject: 'Data export missing two columns', assignee: 'Jordan Lee', assigneeId: 'u2', minutes: -8, severity: 'breaching' }];
