import 'dotenv/config';
import express, { type NextFunction, type Request, type Response } from 'express';
import cors from 'cors';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { PrismaClient, Prisma, Role, Status, Priority, EventType } from '@prisma/client/index';
import { z, ZodError } from 'zod';

const prisma = new PrismaClient();
const app = express();
const port = Number(process.env.PORT ?? 4000);
const reopenDays = Number(process.env.REOPEN_WINDOW_DAYS ?? 7);
const nearBreachMinutes = Number(process.env.SLA_NEAR_BREACH_MINUTES ?? 60);
const jwtSecret = process.env.JWT_SECRET;
if (!process.env.DATABASE_URL || !jwtSecret) throw new Error('DATABASE_URL and JWT_SECRET are required');
app.use(cors({ origin: process.env.CORS_ORIGIN?.split(',') ?? true }));
app.use(express.json({ limit: '1mb' }));

type AuthUser = { id: string; role: Role; name: string; email: string };
declare global { namespace Express { interface Request { user?: AuthUser } } }
const error = (status: number, reason: string, details?: unknown) => Object.assign(new Error(reason), { status, reason, details });
const protectedRoute = (req: Request, _res: Response, next: NextFunction) => {
    const token = req.headers.authorization?.startsWith('Bearer ') ? req.headers.authorization.slice(7) : undefined;
    if (!token) return next(error(403, 'Authentication required: provide a Bearer token.'));
    try { req.user = jwt.verify(token, jwtSecret) as AuthUser; next(); } catch { next(error(403, 'Authentication failed: the token is missing, expired, or invalid.')); }
};
const supervisorOnly = (req: Request, _res: Response, next: NextFunction) => req.user?.role === Role.supervisor ? next() : next(error(403, 'Supervisor role required for this action.'));
const body = <T extends z.ZodTypeAny>(schema: T, req: Request) => schema.parse(req.body) as z.infer<T>;
const idParam = (req: Request) => String(req.params.id);
const priorityMinutes: Record<Priority, number> = { Urgent: 60, High: 240, Normal: 480, Low: 1440 };
const elapsedSeconds = (ticket: { status: Status; createdAt: Date; pendingStartedAt: Date | null; pendingSeconds: number }) => {
    const end = ticket.status === Status.Pending && ticket.pendingStartedAt ? ticket.pendingStartedAt : new Date();
    return Math.max(0, Math.floor((end.getTime() - ticket.createdAt.getTime()) / 1000) - ticket.pendingSeconds);
};
const presentTicket = (ticket: any) => {
    const elapsed = elapsedSeconds(ticket); const target = priorityMinutes[ticket.priority as Priority] * 60; const remaining = target - elapsed;
    return { ...ticket, assignee: ticket.primaryAssignee, collaborators: ticket.collaborators?.map((c: any) => c.user) ?? [], replies: ticket.replies ?? [], events: ticket.events ?? [], sla: { targetSeconds: target, elapsedSeconds: elapsed, remainingSeconds: remaining, breached: remaining < 0, pendingSeconds: ticket.pendingSeconds } };
};
const ticketInclude = { primaryAssignee: { select: { id: true, name: true, email: true, role: true } }, collaborators: { include: { user: { select: { id: true, name: true, email: true, role: true } } } }, replies: { orderBy: { createdAt: 'asc' as const }, include: { author: { select: { id: true, name: true, role: true } } } }, events: { orderBy: { createdAt: 'asc' as const }, include: { actor: { select: { id: true, name: true, role: true } } } } };
const findTicket = (id: string) => prisma.ticket.findUnique({ where: { id }, include: ticketInclude });
const canAct = async (user: AuthUser, id: string) => { if (user.role === Role.supervisor) return true; const t = await prisma.ticket.findFirst({ where: { id, OR: [{ primaryAssigneeId: user.id }, { collaborators: { some: { userId: user.id } } }] }, select: { id: true } }); return Boolean(t); };
const transition: Record<Status, Status[]> = { New: [Status.Open], Open: [Status.Pending, Status.Resolved], Pending: [Status.Open, Status.Resolved], Resolved: [Status.Closed, Status.Open], Closed: [Status.Open] };
const writeStatus = async (tx: Prisma.TransactionClient, ticket: any, next: Status, actorId: string) => {
    const now = new Date(); let pendingSeconds = ticket.pendingSeconds; let pendingStartedAt = ticket.pendingStartedAt;
    if (next === Status.Pending) pendingStartedAt = now;
    if (ticket.status === Status.Pending && next !== Status.Pending && pendingStartedAt) { pendingSeconds += Math.floor((now.getTime() - pendingStartedAt.getTime()) / 1000); pendingStartedAt = null; }
    const updated = await tx.ticket.update({ where: { id: ticket.id }, data: { status: next, pendingStartedAt, pendingSeconds, closedAt: next === Status.Closed ? now : next === Status.Open ? null : ticket.closedAt } });
    await tx.ticketEvent.create({ data: { ticketId: ticket.id, type: EventType.status_change, actorId, oldValue: ticket.status, newValue: next } });
    return updated;
};

app.get('/health', (_req, res) => res.json({ ok: true }));
app.post('/api/auth/login', async (req, res, next) => { try { const input = body(z.object({ email: z.string().email(), password: z.string().min(1) }), req); const user = await prisma.user.findUnique({ where: { email: input.email.toLowerCase() } }); if (!user || !(await bcrypt.compare(input.password, user.passwordHash))) return next(error(401, 'Invalid email or password.')); const safe = { id: user.id, name: user.name, email: user.email, role: user.role }; res.json({ token: jwt.sign(safe, jwtSecret, { expiresIn: '8h' }), user: safe }); } catch (e) { next(e); } });
app.use('/api', protectedRoute);

app.get('/api/users', async (_req, res, next) => { try { res.json(await prisma.user.findMany({ select: { id: true, name: true, email: true, role: true }, orderBy: { name: 'asc' } })); } catch (e) { next(e); } });
app.get('/api/tickets', async (req, res, next) => { try { const q = z.object({ q: z.string().optional(), status: z.nativeEnum(Status).optional(), priority: z.nativeEnum(Priority).optional(), category: z.string().optional(), assignee: z.string().optional(), sort: z.enum(['created_at', 'priority', 'updated_at']).default('created_at'), direction: z.enum(['asc', 'desc']).default('desc'), page: z.coerce.number().int().min(1).default(1), pageSize: z.coerce.number().int().min(1).max(100).default(20), includeArchived: z.coerce.boolean().default(false) }).parse(req.query); const where: Prisma.TicketWhereInput = { ...(q.includeArchived ? {} : { archivedAt: null }), ...(q.status && { status: q.status }), ...(q.priority && { priority: q.priority }), ...(q.category && { category: q.category }), ...(q.assignee && { primaryAssigneeId: q.assignee }), ...(q.q && { OR: [{ subject: { contains: q.q, mode: 'insensitive' } }, { description: { contains: q.q, mode: 'insensitive' } }] }) }; const orderBy = q.sort === 'priority' ? { priority: q.direction } : { [q.sort === 'updated_at' ? 'updatedAt' : 'createdAt']: q.direction }; const [total, rows] = await prisma.$transaction([prisma.ticket.count({ where }), prisma.ticket.findMany({ where, include: ticketInclude, orderBy, skip: (q.page - 1) * q.pageSize, take: q.pageSize })]); res.json({ results: rows.map(presentTicket), total, page: q.page, pageSize: q.pageSize }); } catch (e) { next(e); } });
app.get('/api/tickets/mine', async (req, res, next) => { try { const rows = await prisma.ticket.findMany({ where: { archivedAt: null, OR: [{ primaryAssigneeId: req.user!.id }, { collaborators: { some: { userId: req.user!.id } } }] }, include: ticketInclude, orderBy: { updatedAt: 'desc' } }); res.json(rows.map(presentTicket)); } catch (e) { next(e); } });
app.get('/api/tickets/:id', async (req, res, next) => { try { const t = await findTicket(idParam(req)); if (!t) return next(error(404, 'Ticket not found.')); if (!(await canAct(req.user!, t.id)) && req.user!.role !== Role.supervisor) return next(error(403, 'You may only view tickets assigned to you or shared with you.')); res.json(presentTicket(t)); } catch (e) { next(e); } });
const ticketInput = z.object({ subject: z.string().trim().min(1).max(200), description: z.string().trim().min(1), requester: z.string().trim().min(1).max(320), priority: z.nativeEnum(Priority), category: z.string().trim().min(1).max(80), primaryAssigneeId: z.string().uuid().nullable().optional() });
app.post('/api/tickets', async (req, res, next) => { try { const input = body(ticketInput, req); if (input.primaryAssigneeId && !(await prisma.user.findUnique({ where: { id: input.primaryAssigneeId } }))) return next(error(400, 'primaryAssigneeId does not identify a user.')); const t = await prisma.ticket.create({ data: input, include: ticketInclude }); res.status(201).json(presentTicket(t)); } catch (e) { next(e); } });
app.patch('/api/tickets/:id', async (req, res, next) => { try { const t = await findTicket(idParam(req)); if (!t) return next(error(404, 'Ticket not found.')); if (!(await canAct(req.user!, t.id))) return next(error(403, 'You may only edit tickets assigned to you or shared with you.')); const input = ticketInput.partial().parse(req.body); const updated = await prisma.ticket.update({ where: { id: t.id }, data: input, include: ticketInclude }); res.json(presentTicket(updated)); } catch (e) { next(e); } });
app.post('/api/tickets/:id/status', async (req, res, next) => { try { const t = await prisma.ticket.findUnique({ where: { id: idParam(req) } }); if (!t) return next(error(404, 'Ticket not found.')); if (!(await canAct(req.user!, t.id))) return next(error(403, 'You may only change status on tickets assigned to you or shared with you.')); const nextStatus = body(z.object({ status: z.nativeEnum(Status) }), req).status; if (!transition[t.status].includes(nextStatus)) return next(error(400, `Invalid status transition: ${t.status} can move only to ${transition[t.status].join(', ')}.`)); if (t.status === Status.Closed && nextStatus === Status.Open && (!t.closedAt || Date.now() - t.closedAt.getTime() > reopenDays * 86400000)) return next(error(400, `Reopening is allowed only within ${reopenDays} days of closing.`)); const updated = await prisma.$transaction(tx => writeStatus(tx, t, nextStatus, req.user!.id)); res.json(presentTicket(await findTicket(updated.id))); } catch (e) { next(e); } });

app.post('/api/tickets/:id/archive', async (req, res, next) => { try { const t = await prisma.ticket.findUnique({ where: { id: idParam(req) } }); if (!t) return next(error(404, 'Ticket not found.')); if (!(await canAct(req.user!, t.id))) return next(error(403, 'You may only archive tickets assigned to you or shared with you.')); res.json(presentTicket(await prisma.ticket.update({ where: { id: t.id }, data: { archivedAt: new Date() }, include: ticketInclude }))); } catch (e) { next(e); } });
app.post('/api/tickets/:id/restore', async (req, res, next) => { try { const t = await prisma.ticket.findUnique({ where: { id: idParam(req) } }); if (!t) return next(error(404, 'Ticket not found.')); if (!(await canAct(req.user!, t.id))) return next(error(403, 'You may only restore tickets assigned to you or shared with you.')); res.json(presentTicket(await prisma.ticket.update({ where: { id: t.id }, data: { archivedAt: null }, include: ticketInclude }))); } catch (e) { next(e); } });

const replyInput = z.object({ body: z.string().trim().min(1).max(10000), is_internal: z.boolean().default(false) });
app.get('/api/tickets/:id/replies', async (req, res, next) => { try { const id = idParam(req); if (!(await canAct(req.user!, id))) return next(error(403, 'You may only view replies for tickets assigned to you or shared with you.')); res.json(await prisma.reply.findMany({ where: { ticketId: id }, orderBy: { createdAt: 'asc' }, include: { author: { select: { id: true, name: true, role: true } } } })); } catch (e) { next(e); } });
app.post('/api/tickets/:id/replies', async (req, res, next) => { try { const id = idParam(req); const t = await prisma.ticket.findUnique({ where: { id } }); if (!t) return next(error(404, 'Ticket not found.')); if (!(await canAct(req.user!, id))) return next(error(403, 'You may only reply to tickets assigned to you or shared with you.')); const input = body(replyInput, req); const reply = await prisma.$transaction(async tx => { const created = await tx.reply.create({ data: { ticketId: id, authorId: req.user!.id, body: input.body, isInternal: input.is_internal }, include: { author: { select: { id: true, name: true, role: true } } } }); await tx.ticketEvent.create({ data: { ticketId: id, type: EventType.reply, actorId: req.user!.id, newValue: input.is_internal ? 'internal' : 'public' } }); if (t.status === Status.Pending && !input.is_internal) await writeStatus(tx, t, Status.Open, req.user!.id); else await tx.ticket.update({ where: { id }, data: { updatedAt: new Date() } }); return created; }); res.status(201).json(reply); } catch (e) { next(e); } });

app.post('/api/tickets/:id/collaborators', async (req, res, next) => { try { const id = idParam(req); if (req.user!.role !== Role.supervisor && !(await canAct(req.user!, id))) return next(error(403, 'Only a supervisor or ticket participant may manage collaborators.')); const input = body(z.object({ userId: z.string().uuid() }), req); const collaborator = await prisma.ticketCollaborator.create({ data: { ticketId: id, userId: input.userId }, include: { user: { select: { id: true, name: true, email: true, role: true } } } }); res.status(201).json(collaborator); } catch (e) { next(e); } });
app.delete('/api/tickets/:id/collaborators/:userId', async (req, res, next) => { try { const id = idParam(req); if (req.user!.role !== Role.supervisor && !(await canAct(req.user!, id))) return next(error(403, 'Only a supervisor or ticket participant may manage collaborators.')); await prisma.ticketCollaborator.delete({ where: { ticketId_userId: { ticketId: id, userId: String(req.params.userId) } } }); res.status(204).send(); } catch (e) { next(e); } });

const assignmentInput = z.object({ assigneeId: z.string().uuid() });
const reassign = async (id: string, assigneeId: string, actor: AuthUser) => { const t = await prisma.ticket.findUnique({ where: { id } }); if (!t) return { success: false, reason: 'Ticket not found.' }; if (actor.role !== Role.supervisor && !(await canAct(actor, id))) return { success: false, reason: 'You may only reassign tickets assigned to you or shared with you.' }; if (actor.role !== Role.supervisor && t.primaryAssigneeId === actor.id && assigneeId !== actor.id) return { success: false, reason: 'Agents cannot reassign a ticket away from themselves.' }; const target = await prisma.user.findUnique({ where: { id: assigneeId } }); if (!target) return { success: false, reason: 'Assignee not found.' }; await prisma.$transaction(async tx => { await tx.ticket.update({ where: { id }, data: { primaryAssigneeId: assigneeId } }); await tx.ticketEvent.create({ data: { ticketId: id, type: EventType.reassignment, actorId: actor.id, oldValue: t.primaryAssigneeId, newValue: assigneeId } }); }); return { success: true }; };
app.post('/api/tickets/:id/reassign', supervisorOnly, async (req, res, next) => { try { const input = body(assignmentInput, req); const result = await reassign(idParam(req), input.assigneeId, req.user!); if (!result.success) return next(error(400, result.reason!)); res.json(await findTicket(idParam(req))); } catch (e) { next(e); } });
app.post('/api/tickets/bulk/reassign', async (req, res, next) => { try { const input = body(z.object({ ticketIds: z.array(z.string().uuid()).min(1), assigneeId: z.string().uuid() }), req); const results = await Promise.all(input.ticketIds.map(async ticketId => ({ ticketId, ...(await reassign(ticketId, input.assigneeId, req.user!)) }))); res.json(results); } catch (e) { next(e); } });
app.post('/api/tickets/bulk/close', async (req, res, next) => { try { const input = body(z.object({ ticketIds: z.array(z.string().uuid()).min(1) }), req); const results = await Promise.all(input.ticketIds.map(async ticketId => { const t = await prisma.ticket.findUnique({ where: { id: ticketId } }); if (!t) return { ticketId, success: false, reason: 'Ticket not found.' }; if (!(await canAct(req.user!, ticketId))) return { ticketId, success: false, reason: 'You are not allowed to close this ticket.' }; if (t.status !== Status.Resolved) return { ticketId, success: false, reason: 'Only Resolved tickets can be closed.' }; await prisma.$transaction(tx => writeStatus(tx, t, Status.Closed, req.user!.id)); return { ticketId, success: true }; })); res.json(results); } catch (e) { next(e); } });

const querySchema = z.object({ q: z.string().optional(), status: z.nativeEnum(Status).optional(), priority: z.nativeEnum(Priority).optional(), category: z.string().optional(), assignee: z.string().optional(), sort: z.enum(['created_at', 'priority', 'updated_at']).default('created_at'), direction: z.enum(['asc', 'desc']).default('desc'), includeArchived: z.coerce.boolean().default(false) });
const queueWhere = (q: z.infer<typeof querySchema>): Prisma.TicketWhereInput => ({ ...(q.includeArchived ? {} : { archivedAt: null }), ...(q.status && { status: q.status }), ...(q.priority && { priority: q.priority }), ...(q.category && { category: q.category }), ...(q.assignee && { primaryAssigneeId: q.assignee }), ...(q.q && { OR: [{ subject: { contains: q.q, mode: 'insensitive' } }, { description: { contains: q.q, mode: 'insensitive' } }] }) });
app.get('/api/tickets/export', async (req, res, next) => { try { const q = querySchema.parse(req.query); const rows = await prisma.ticket.findMany({ where: queueWhere(q), include: { primaryAssignee: true }, orderBy: q.sort === 'priority' ? { priority: q.direction } : { [q.sort === 'updated_at' ? 'updatedAt' : 'createdAt']: q.direction } }); const quote = (value: unknown) => `"${String(value ?? '').replaceAll('"', '""')}"`; const csv = ['id,subject,requester,priority,category,status,assignee,created_at,updated_at', ...rows.map(t => [t.id, t.subject, t.requester, t.priority, t.category, t.status, t.primaryAssignee?.name, t.createdAt.toISOString(), t.updatedAt.toISOString()].map(quote).join(','))].join('\n'); res.type('text/csv').set('Content-Disposition', 'attachment; filename="queuewise-tickets.csv"').send(csv); } catch (e) { next(e); } });

const activeAlert = (t: any) => { const elapsed = elapsedSeconds(t); const remaining = priorityMinutes[t.priority as Priority] * 60 - elapsed; return { remaining, severity: remaining < 0 ? 'breaching' : 'at-risk' as const }; };
const syncAlerts = async () => { const tickets = await prisma.ticket.findMany({ where: { archivedAt: null, status: { in: [Status.New, Status.Open, Status.Pending] } }, include: { slaAlerts: { orderBy: { breachedAt: 'desc' }, take: 1 } } }); for (const t of tickets) { const alert = activeAlert(t); if (alert.remaining <= nearBreachMinutes * 60) { const latest = t.slaAlerts[0]; if (!latest || (latest.acknowledgedAt && latest.acknowledgedAt < t.updatedAt)) await prisma.slaAlert.create({ data: { ticketId: t.id, breachedAt: new Date() } }); } } };
app.get('/api/alerts', async (_req, res, next) => { try { await syncAlerts(); const rows = await prisma.slaAlert.findMany({ where: { acknowledgedAt: null }, include: { ticket: { include: { primaryAssignee: true } } }, orderBy: { breachedAt: 'asc' } }); res.json(rows.map(a => { const current = activeAlert(a.ticket); return { id: a.id, ticketId: a.ticketId, subject: a.ticket.subject, assignee: a.ticket.primaryAssignee?.name ?? 'Unassigned', assigneeId: a.ticket.primaryAssigneeId, minutes: Math.ceil(current.remaining / 60), severity: current.severity, breachedAt: a.breachedAt }; })); } catch (e) { next(e); } });
app.get('/api/alerts/count', async (_req, res, next) => { try { await syncAlerts(); res.json({ count: await prisma.slaAlert.count({ where: { acknowledgedAt: null } }) }); } catch (e) { next(e); } });
app.post('/api/alerts/:id/acknowledge', async (req, res, next) => { try { const alert = await prisma.slaAlert.findUnique({ where: { id: idParam(req) }, include: { ticket: true } }); if (!alert) return next(error(404, 'SLA alert not found.')); if (alert.ticket.primaryAssigneeId !== req.user!.id) return next(error(403, 'Only the ticket primary assignee may acknowledge this alert.')); const updated = await prisma.slaAlert.update({ where: { id: alert.id }, data: { acknowledgedAt: new Date(), acknowledgedBy: req.user!.id } }); res.json(updated); } catch (e) { next(e); } });

app.get('/api/dashboard/summary', async (_req, res, next) => { try { const week = new Date(Date.now() - 7 * 86400000); await syncAlerts(); const [open, pending, resolved, breaching] = await prisma.$transaction([prisma.ticket.count({ where: { status: Status.Open, archivedAt: null } }), prisma.ticket.count({ where: { status: Status.Pending, archivedAt: null } }), prisma.ticket.count({ where: { status: Status.Resolved, updatedAt: { gte: week }, archivedAt: null } }), prisma.slaAlert.count({ where: { acknowledgedAt: null, ticket: { archivedAt: null } } })]); res.json({ open, pending, resolvedThisWeek: resolved, breaching }); } catch (e) { next(e); } });
app.get('/api/dashboard/by-status', async (_req, res, next) => { try { const rows = await prisma.ticket.groupBy({ by: ['status'], _count: { _all: true }, where: { archivedAt: null } }); res.json(rows.map(x => ({ status: x.status, count: x._count._all }))); } catch (e) { next(e); } });
app.get('/api/dashboard/by-agent', async (_req, res, next) => { try { const rows = await prisma.ticket.groupBy({ by: ['primaryAssigneeId'], _count: { _all: true }, where: { archivedAt: null } }); const users = await prisma.user.findMany({ select: { id: true, name: true } }); res.json(rows.map(x => ({ agentId: x.primaryAssigneeId, agent: users.find(u => u.id === x.primaryAssigneeId)?.name ?? 'Unassigned', count: x._count._all }))); } catch (e) { next(e); } });
app.get('/api/dashboard/resolved-per-week', async (_req, res, next) => { try { const since = new Date(Date.now() - 56 * 86400000); const events = await prisma.ticketEvent.findMany({ where: { type: EventType.status_change, newValue: Status.Resolved, createdAt: { gte: since } }, select: { createdAt: true } }); const result = Array.from({ length: 8 }, (_, index) => { const start = new Date(Date.now() - (7 - index) * 7 * 86400000); start.setHours(0, 0, 0, 0); const end = new Date(start.getTime() + 7 * 86400000); return { weekStart: start.toISOString().slice(0, 10), count: events.filter(e => e.createdAt >= start && e.createdAt < end).length }; }); res.json(result); } catch (e) { next(e); } });

app.use((err: any, _req: Request, res: Response, _next: NextFunction) => { const errorText = String(err?.message ?? ''); const databaseUnavailable = err?.name === 'PrismaClientInitializationError' || err?.code === 'P1000' || err?.code === 'P1001' || /authentication failed against database|can't reach database server/i.test(errorText); const status = databaseUnavailable ? 503 : err instanceof ZodError ? 400 : err.status ?? 500; const reason = databaseUnavailable ? 'Database unavailable: check DATABASE_URL, PostgreSQL credentials, and that PostgreSQL is running.' : err instanceof ZodError ? 'Invalid request input.' : err.reason ?? 'Internal server error.'; res.status(status).json({ error: { reason, ...(err instanceof ZodError ? { details: err.issues } : err.details ? { details: err.details } : {}) } }); });
app.listen(port, () => console.log(`Queuewise API listening on port ${port}`));
